### ISSUE TITLE
Inverse of Scattering Transform

### ISSUE THREAD

**Issue by rbunn80110** [edouardoyallon/pyscatwave#10]
I'm curious how you might reverse the scatter transform?  For example, perform the scatter operation on an image, then do the inverse and get the image back.  Is that possible?

**Comment by edouardoyallon** [comment]
We will release a software soon! The inverse operation is often possible, yet in several case no or few regularization might be enough. 
Some papers might interest you, like: https://arxiv.org/pdf/1609.05502.pdf

**Comment by rbunn80110** [comment]
Thanks!

**Comment by edouardoyallon** [comment]
https://github.com/edouardoyallon/pyscatwave/blob/master/scatwave/differentiable.py
