### ISSUE TITLE
run pyscatwave without cuda

### ISSUE THREAD

**Issue by asberk** [edouardoyallon/pyscatwave#13]
I tried to install `pyscatwave`, but do not have CUDA (so I cannot install `skcuda`). 
I can run `python setup.py install` without issue, but when I run `import scatwave` I get the following
```python
---------------------------------------------------------------
ImportError                   Traceback (most recent call last)
<ipython-input-2-a2d06b630338> in <module>()
----> 1 import scatwave

~/anaconda/lib/python3.5/site-packages/scatwave-0.0.1-py3.5.egg/scatwave/__init__.py in <module>()
      6 
      7 
----> 8 from .scattering import Scattering
      9 from . import utils

~/anaconda/lib/python3.5/site-packages/scatwave-0.0.1-py3.5.egg/scatwave/scattering.py in <module>()
      8 import warnings
      9 import torch
---> 10 from .utils import cdgmm, Modulus, Periodize, Fft
     11 from .filters_bank import filters_bank
     12 from torch.legacy.nn import SpatialReflectionPadding as pad_function

~/anaconda/lib/python3.5/site-packages/scatwave-0.0.1-py3.5.egg/scatwave/utils.py in <module>()
      6 
      7 import torch
----> 8 from skcuda import cublas, cufft
      9 from pynvrtc.compiler import Program
     10 import numpy as np

ImportError: No module named 'skcuda'
```

Is it possible to simply remove this dependency and still run `pyscatwave`? Or would it be significantly more complicated than that?

**Comment by edouardoyallon** [comment]
Thanks for pointing this out. This will be fixed in the new version(soon)

Best,

**Comment by nshervt** [comment]
It seems that this issue still exists. Any solutions?

**Comment by edouardoyallon** [comment]
Why don't you use kymat.io ?

**Comment by nshervt** [comment]
I was trying to run the Hybrid code, which is written based on pyscatwave.

**Comment by edouardoyallon** [comment]
Right, so we will need to reimplement those models with kymat.io at some points. You can try to modify internal routines s.t. they're performed on CPU.. but I'd suggest to directly plug kymatio. The output should be the same AFAIR.

**Comment by nshervt** [comment]
Sounds good. Tnx!
