### ISSUE TITLE
How to calculate K, the output dimension of the output of scattering?

### ISSUE THREAD

**Issue by deepakanandece** [edouardoyallon/pyscatwave#14]
Please provide details about how to calculate K, the output dimension of the output of scattering.

**Comment by eugenium** [comment]
In channels it will be (1 + 8 * J + 8 * 8 * J * (J - 1) / 2)  for each color (x3)
and spatially N / (2 ** J)

There is an example here
https://github.com/edouardoyallon/scalingscattering/blob/master/imagenet/models/scatter_resnet.py#L55
