### ISSUE TITLE
Is there an implementation of 1-D Scattering Transform?

### ISSUE THREAD

**Issue by rafellerc** [edouardoyallon/pyscatwave#17]
In Mallat's work, there are implementations for the 1-D and 2-D Scattering Networks, for working with audio and images respectively. Does your code implement at all the 1-D Scattering Transform? And if not, have you or another one of Mallat's students have implemented the 1-D Scattering Transform in python or C++, or is the only implementation available Mallat's Matlab version? (Here I'm assuming that your 2-D Scattering implementation is NOT suitable for audio analysis by setting one of the dimensions to 1, please correct me if I'm wrong)

**Comment by edouardoyallon** [comment]
Hi, no, the code does not implement 1D. We're in discussion to potentially release a 1D code. Maybe Joan Bruna has one, you could ask.

Best
EO

**Comment by edouardoyallon** [comment]
https://www.kymat.io/
