### ISSUE TITLE
Reconstructing the input image

### ISSUE THREAD

**Issue by deepUnlearn** [edouardoyallon/pyscatwave#23]
Is there any easy hack to use your code for reconstructing the input image ?

**Comment by eugenium** [comment]
Hi, you can do this by importing the scattering version in the experimantal differentiable.py file that should let you differentiate. 

I added an example on this (courtesy of @gabrielhuang)  that should get you most of the way there https://github.com/edouardoyallon/pyscatwave/blob/master/examples/reconstruction_exp.py

Unfortunately we are soon deprecating this code base so won't be able to support it heavily. There will be a heavily refined new package available within the next 2 months that subsumes all this functionality.

**Comment by deepUnlearn** [comment]
Great Thanks for the quick response.

**Comment by edouardoyallon** [comment]
https://www.kymat.io/

**Comment by ghost** [comment]
Thanks!
