### ISSUE TITLE
MNIST example is incorrect

### ISSUE THREAD

**Issue by sebastiankmiec** [edouardoyallon/pyscatwave#25]
I see you based your code off of "https://github.com/pytorch/tnt/blob/master/example/mnist.py".

You forgot to reset the "classerr" meter. So when you call "engine.test", the accuracy that is printed out is the average classification accuracy of testing and training, not just testing.

**Comment by sebastiankmiec** [comment]
I would add " classerr.reset()" at the end of "on_end_epoch()".

**Comment by edouardoyallon** [comment]
Thanks for your feedback. We removed it from www.kymat.io thus it is not necessary to maintain this.
