### ISSUE TITLE
I have a question about reconstruction_exp.py

### ISSUE THREAD

**Issue by strawberry1996** [edouardoyallon/pyscatwave#28]
I write a code to call the encode_processed function of the reconstruction_exp.py, but it have a little problem, I want to scattering a image use this function, and then call the decode function of the reconstruction_exp.py to recovery this picture. I don't know if I can do that. And I can't find test code in your project would you please give me a test code about how to call these two function?  Thanks very much.

**Comment by edouardoyallon** [comment]
https://www.kymat.io/gallery_2d/plot_invert_scattering.html
