### ISSUE TITLE
Implementation of pyscatwave using DL library primitives

### ISSUE THREAD

**Issue by tdeboissiere** [edouardoyallon/pyscatwave#3]
Thanks for releasing that code !

I have not analyzed the scattering implementation thoroughly so this may not be a well-informed question but would it be feasible to write a pure pytorch (or tensorflow or theano for that matter) implementation using only the library's primitives ?

If it is, have you tried such an implementation and was the performance satisfying?

**Comment by eugenium** [comment]
Hi thanks for the question. Indeed many of the core operations using custom cuda kernels can be replaced with pure pytorch at a cost of ~2x slowdown. However, the reliance on cuFFT can't be easily removed without a drastic speed decrease.

**Comment by tdeboissiere** [comment]
Thanks for the quick reply. On a related note, how hard do you think the implementation of a backward pass (to be able to use this new module anywhere in a network) would be ?

**Comment by edouardoyallon** [comment]
Thanks again for the question. We are currently working on it, and we will release soon this feature, with several applications.

**Comment by ghost** [comment]
@edouardoyallon  Any update regarding when backprop could be made to work through the transform? Even if unpolished it would be nice.
