### ISSUE TITLE
cublasNotInitialized

### ISSUE THREAD

**Issue by shiningsurya** [edouardoyallon/pyscatwave#4]
All the drivers/modules have been installed and verified. 
It throws an '`cublasNotInitialized`' error when I run `scat(x)`.  
Though, I can run `skcuda.cublas.cublasCreate()` in python.

**Comment by edouardoyallon** [comment]
Hi. Thanks for reporting it. Can you copy/paste the error?

**Comment by szagoruyko** [comment]
@shiningsurya the code uses torch cublas state, there is no need to initialize state with skcuda

**Comment by shiningsurya** [comment]
Yeah, I realized that after seeing the code. 
`torch.cuda.current_blas_handle()` returns a valid number. 
`torch.cuda.current_stream()._as_parameter_` returns a `c_void_p(None)` which seems like a Null Pointer object. 
You have any idea about this?  
..
The error is reproduced below.. I hope you can follow through the error. 
> ---------------------------------------------------------------------------
> cublasNotInitialized                      Traceback (most recent call last)
> <ipython-input-1-a9d975bb70c1> in <module>()
>       5 x = torch.randn(1, 3, 32, 32).cuda()
>       6 
> ----> 7 print scat(x).size()
> 
> /usr/local/lib/python2.7/dist-packages/scatwave-0.0.1-py2.7.egg/scatwave/scattering.pyc in __call__(self, input)
>     160 
>     161     def __call__(self, input):
> --> 162         return self.forward(input)
> 
> /usr/local/lib/python2.7/dist-packages/scatwave-0.0.1-py2.7.egg/scatwave/scattering.pyc in forward(self, input)
>     122 
>     123         # First low pass filter
> --> 124         U_1_c = periodize(cdgmm(U_0_c, phi[0], jit=self.jit), k=2**J)
>     125 
>     126         U_J_r = fft(U_1_c, 'C2R')
> 
> /usr/local/lib/python2.7/dist-packages/scatwave-0.0.1-py2.7.egg/scatwave/utils.pyc in cdgmm(A, B, jit, inplace)
>     278         handle = torch.cuda.current_blas_handle()
>     279         stream = torch.cuda.current_stream()._as_parameter_
> --> 280         cublas.cublasSetStream(handle, stream)
>     281         cublas.cublasCdgmm(handle, 'l', m, n, A.data_ptr(), lda, B.data_ptr(), incx, C.data_ptr(), ldc)
>     282         return C
> 
> /usr/local/lib/python2.7/dist-packages/skcuda/cublas.pyc in cublasSetStream(handle, id)
>     325 
>     326     status = _libcublas.cublasSetStream_v2(handle, id)
> --> 327     cublasCheckStatus(status)
>     328 
>     329 _libcublas.cublasGetStream_v2.restype = int
> 
> /usr/local/lib/python2.7/dist-packages/skcuda/cublas.pyc in cublasCheckStatus(status)
>     163     if status != 0:
>     164         try:
> --> 165             raise cublasExceptions[status]
>     166         except KeyError:
>     167             raise cublasError

**Comment by szagoruyko** [comment]
@shiningsurya null pointer shouldn't be a problem. what version of skcuda and pytorch are you using?

**Comment by shiningsurya** [comment]
skcuda 0.5.1 
pytorch 0.1.11

**Comment by shiningsurya** [comment]
Yeah 
so it turns out it there are many things in the background and I got it to work for me. 

I moved to Ubuntu 14.04 from 16.04, used conda and pip with CUDA 8.0 and CuDNN 5.1. Any other combination is not compatible.

Learnt it the hard way.

**Comment by szagoruyko** [comment]
@shiningsurya oyoyoy, sorry about that, we will try to improve the code. There are 2 things we could do:
 * replace CDGMM with expand + a hack to make psi and phi real = im, don't really want to do that
 * have a compiled part, which we had initially, but moved to ctypes

**Comment by shiningsurya** [comment]
Watching this for sure. 

Having a compiled part is even more painful to install right?

**Comment by edouardoyallon** [comment]
No, it's few lines using the cffi of pytorch, yet we decided to remove it for the sake of simplicity and using fast high-level routines, like skcuda. I do not like the idea of the hack as it does not permit to use any filterbanks.

**Comment by angelleng** [comment]
Hey I'm having the same problem here, and I'm not quite sure what's the solution after reading this thread. 
I have the same configurations (latest conda and python, cuda 8.0, cudnn 5.1) but it still gives me this error.

**Comment by shiningsurya** [comment]
Hey @angelleng 

Can you initialize `torch.Tensor` on CUDA? Is it throwing you an error in that? 
Have you tried importing `skcuda` in an iPython shell? Also, what is your output for `torch.cuda.current_blas_handle()` and `torch.cuda.current_stream()._as_parameter_`

**Comment by angelleng** [comment]
I recompiled pytorch under cuda 8.0 and it worked. My pytorch was installed under cuda 7.5. 

Also is cuda 7.5 is not supported?

**Comment by shiningsurya** [comment]
@angelleng 
While installing PyTorch, I ran into [https://discuss.pytorch.org/t/installation-error-memcpy-was-not-declared-in-this-scope/1444](this) error. 
Heeding their advise, I moved to CUDA 8.0.
