### ISSUE TITLE
which part is gaussian smoothing? 

### ISSUE THREAD

**Issue by angelleng** [edouardoyallon/pyscatwave#7]
Not quite an issue but a question I have on the code: where is the gaussian smoothing implemented? My guess is the Phi filter, but that doesn't look like a gaussian filter. What am I missing?

**Comment by edouardoyallon** [comment]
Hi, did you plot the Phi filter? why isn't it a gaussian filter

**Comment by angelleng** [comment]
yes: 
```
phi_signal = filters_bank.gabor_2d(8, 8, 0.8 * 2**(2-1), 0, 0, offset=0) 
plt.imshow(np.real(phi_signal))
plt.colorbar()
```
https://screencast.com/t/kVWrh2eof 

I think I'm confused because I'm not familiar with signal processing. I was expecting the filters to have the size of 2 to the power of scale, and look like a 2d wavelet/gaussian distribution, but here it is the size of the input data, and they have lower values in the middle and higher on the corners. I assume you are not applying the filters through convolution? What is the method you are using then?

**Comment by edouardoyallon** [comment]
All our convolutions are implemented via Fourier.

There is a convention in signal processing (and FFT libraries): 0 frequency should be at the (0,0) position. I used the same convention in the real domain, which is quite arbitrary. Also, it permits avoiding an extra non-necessary phase. You can use fftshift to get rid of this.
