### ISSUE TITLE
Weird unpredictable behaviour

### ISSUE THREAD

**Issue by MendesO** [edouardoyallon/pyscatwave#8]
Hi!
I tried using the lib and got some weird unpredictable behaviour. I just created a matrix A, computed the scattering transform of A and 1.01*A, and printed the ratio between the two outputs.
`
A = torch.FloatTensor(np.ones((1,1,4,4)))

A[0,0,0,0]=3

scat = Scattering(M=4, N=4, J=2).cpu()

res1 = scat(A).numpy().copy().squeeze()

res2 = scat(1.01*A).numpy().copy().squeeze()

print(res2/res1)
`

When I repeat this code, which as far as I understand should always give the same result, I get totally different matrices. Sometimes with an order of magnitude of 1, sometimes 10^{-3}, 10^{25}, 10^{20} etc.
I checked and there is no 'rand' function in your code, what the hell is it doing? ^^

**Comment by edouardoyallon** [comment]
Can you try with larger signals? If this is still the case, then there is indeed something missing/a bug. I guess you're running into round-off errors, as I did not specifically intend to support very small signals (better to pad them), and there might be some dependancies in the length that lead to what you do observe.

**Comment by MendesO** [comment]
Round-off errors are violent! 
You are right, I tried other power of two sizes (20 run, taking the max of standard deviation over coordinates), and 4 is the only one for which I get absurd results. From 8 onwards, I get standard deviation of the order of 10^{-7}.
(Of course, nothing for 2, since your code works only if the size can be divided by 4, but this sounds like a reasonable requirement).

A+ !

**Comment by edouardoyallon** [comment]
Well, all of this is due to conditioning & mantissa: with single floats on GPUs, your precision is about 10^-6 (which is around the normalized std you reported), and I guess a very small number like that occurs, then inverting such numbers is pretty much ill-conditioned! Indeed, there are many improvements to do, feel free to push...
