### ISSUE TITLE
Is calculating a derivative possible?

### ISSUE THREAD

**Issue by lolz0r** [edouardoyallon/pyscatwave#9]
Hi,
Good work with this technique! I think its use could be expanded beyond simple feed-forward classifiers. In particular, I think it could be useful in generative neural networks. 

Is there a means to calculate a gradient through this such that this module could be used as an intermediate part of a larger computation graph?

Best wishes,
Michael

**Comment by edouardoyallon** [comment]
Hi, thanks for your message. Yes, we're working on that. We have a version that we'll release later, when we'll have some more time.
Best,
EO

**Comment by olivierhenaff** [comment]
Hi guys,

Was there ever any update on this? I too would be very interested in back-propagating through the scattering transform. 

Thanks in advance,

Olivier

**Comment by edouardoyallon** [comment]
https://github.com/edouardoyallon/pyscatwave/blob/master/scatwave/differentiable.py

**Comment by edouardoyallon** [comment]
https://www.kymat.io/
